import { Question } from "./types"

// Banco de 300 preguntas con 4 opciones cada una
// La respuesta correcta es siempre el index 0 (primera opcion) en el array original.
// Se barajan al generar el examen.

const questionBank: Question[] = [
  // --- CIENCIAS NATURALES (1-50) ---
  { id: 1, question: "Cual es el planeta mas grande del sistema solar?", options: ["Jupiter", "Saturno", "Urano", "Neptuno"], correctAnswer: 0 },
  { id: 2, question: "Cual es el elemento quimico con simbolo 'O'?", options: ["Oxigeno", "Oro", "Osmio", "Oganesson"], correctAnswer: 0 },
  { id: 3, question: "Cuantos huesos tiene el cuerpo humano adulto?", options: ["206", "208", "300", "195"], correctAnswer: 0 },
  { id: 4, question: "Que organo del cuerpo humano produce insulina?", options: ["Pancreas", "Higado", "Rinon", "Estomago"], correctAnswer: 0 },
  { id: 5, question: "Cual es la velocidad de la luz en el vacio?", options: ["300,000 km/s", "150,000 km/s", "500,000 km/s", "100,000 km/s"], correctAnswer: 0 },
  { id: 6, question: "Cual es la formula quimica del agua?", options: ["H2O", "CO2", "NaCl", "H2SO4"], correctAnswer: 0 },
  { id: 7, question: "Que gas es esencial para la respiracion humana?", options: ["Oxigeno", "Nitrogeno", "Hidrogeno", "Helio"], correctAnswer: 0 },
  { id: 8, question: "Cual es el hueso mas largo del cuerpo humano?", options: ["Femur", "Tibia", "Humero", "Radio"], correctAnswer: 0 },
  { id: 9, question: "Que tipo de celula no tiene nucleo?", options: ["Procariota", "Eucariota", "Vegetal", "Animal"], correctAnswer: 0 },
  { id: 10, question: "Cual es el planeta mas cercano al Sol?", options: ["Mercurio", "Venus", "Tierra", "Marte"], correctAnswer: 0 },
  { id: 11, question: "Que es la fotosintesis?", options: ["Proceso de las plantas para producir alimento con luz solar", "Proceso de respiracion celular", "Proceso de division celular", "Proceso de digestion"], correctAnswer: 0 },
  { id: 12, question: "Cual es el metal mas abundante en la corteza terrestre?", options: ["Aluminio", "Hierro", "Cobre", "Oro"], correctAnswer: 0 },
  { id: 13, question: "Que organo es responsable de filtrar la sangre?", options: ["Rinon", "Higado", "Corazon", "Pulmon"], correctAnswer: 0 },
  { id: 14, question: "Cual es la unidad basica de la vida?", options: ["La celula", "El atomo", "La molecula", "El tejido"], correctAnswer: 0 },
  { id: 15, question: "Que vitamina produce la piel con la luz solar?", options: ["Vitamina D", "Vitamina C", "Vitamina A", "Vitamina B12"], correctAnswer: 0 },
  { id: 16, question: "Cual es el oceano mas grande del mundo?", options: ["Pacifico", "Atlantico", "Indico", "Artico"], correctAnswer: 0 },
  { id: 17, question: "Que tipo de energia tiene un objeto en movimiento?", options: ["Cinetica", "Potencial", "Termica", "Quimica"], correctAnswer: 0 },
  { id: 18, question: "Cual es la capa mas externa de la Tierra?", options: ["Corteza", "Manto", "Nucleo externo", "Nucleo interno"], correctAnswer: 0 },
  { id: 19, question: "Que gas producen las plantas durante la fotosintesis?", options: ["Oxigeno", "Dioxido de carbono", "Nitrogeno", "Hidrogeno"], correctAnswer: 0 },
  { id: 20, question: "Cual es el animal mas rapido del mundo?", options: ["Guepardo", "Leon", "Aguila", "Caballo"], correctAnswer: 0 },
  { id: 21, question: "Que es el ADN?", options: ["Acido desoxirribonucleico", "Acido diclorico natural", "Agente de nutricion", "Acido dinitrico alcalino"], correctAnswer: 0 },
  { id: 22, question: "Cual es la temperatura de ebullicion del agua al nivel del mar?", options: ["100 grados Celsius", "90 grados Celsius", "110 grados Celsius", "80 grados Celsius"], correctAnswer: 0 },
  { id: 23, question: "Que parte del cerebro controla el equilibrio?", options: ["Cerebelo", "Cerebro", "Bulbo raquideo", "Hipotalamo"], correctAnswer: 0 },
  { id: 24, question: "Cual es el gas mas abundante en la atmosfera?", options: ["Nitrogeno", "Oxigeno", "Dioxido de carbono", "Argon"], correctAnswer: 0 },
  { id: 25, question: "Que tipo de roca se forma por enfriamiento de magma?", options: ["Ignea", "Sedimentaria", "Metamorfica", "Caliza"], correctAnswer: 0 },
  { id: 26, question: "Cual es el musculo mas grande del cuerpo humano?", options: ["Gluteo mayor", "Cuadriceps", "Biceps", "Pectoral"], correctAnswer: 0 },
  { id: 27, question: "Que es un ecosistema?", options: ["Conjunto de seres vivos y su ambiente", "Solo los animales de una zona", "Solo las plantas de una zona", "El clima de una region"], correctAnswer: 0 },
  { id: 28, question: "Cual es el punto de fusion del hielo?", options: ["0 grados Celsius", "100 grados Celsius", "-10 grados Celsius", "32 grados Celsius"], correctAnswer: 0 },
  { id: 29, question: "Que sistema del cuerpo incluye el corazon y los vasos sanguineos?", options: ["Sistema circulatorio", "Sistema nervioso", "Sistema digestivo", "Sistema respiratorio"], correctAnswer: 0 },
  { id: 30, question: "Cual es la estrella mas cercana a la Tierra?", options: ["El Sol", "Alfa Centauri", "Sirio", "Betelgeuse"], correctAnswer: 0 },
  { id: 31, question: "Que es la mitosis?", options: ["Division celular que produce celulas identicas", "Union de celulas", "Muerte celular", "Proceso de nutricion celular"], correctAnswer: 0 },
  { id: 32, question: "Cual es el organo mas grande del cuerpo humano?", options: ["La piel", "El higado", "El cerebro", "Los pulmones"], correctAnswer: 0 },
  { id: 33, question: "Que es un atomo?", options: ["La unidad basica de la materia", "Una celula pequena", "Un tipo de molecula", "Una particula de luz"], correctAnswer: 0 },
  { id: 34, question: "Cual es la funcion principal de los globulos rojos?", options: ["Transportar oxigeno", "Combatir infecciones", "Coagular la sangre", "Producir anticuerpos"], correctAnswer: 0 },
  { id: 35, question: "Que causa las mareas en los oceanos?", options: ["La gravedad de la Luna y el Sol", "El viento", "La rotacion terrestre", "Las corrientes marinas"], correctAnswer: 0 },
  { id: 36, question: "Cual es el estado de la materia del vapor?", options: ["Gaseoso", "Liquido", "Solido", "Plasma"], correctAnswer: 0 },
  { id: 37, question: "Que organo produce la bilis?", options: ["Higado", "Pancreas", "Estomago", "Rinon"], correctAnswer: 0 },
  { id: 38, question: "Cual es la unidad de medida de la fuerza?", options: ["Newton", "Julio", "Vatio", "Pascal"], correctAnswer: 0 },
  { id: 39, question: "Que es la gravedad?", options: ["Fuerza de atraccion entre masas", "Tipo de energia", "Fuerza magnetica", "Fuerza electrica"], correctAnswer: 0 },
  { id: 40, question: "Cual es el proceso de transformacion de larva a adulto en insectos?", options: ["Metamorfosis", "Mitosis", "Meiosis", "Simbiosis"], correctAnswer: 0 },
  { id: 41, question: "Que planeta es conocido como el planeta rojo?", options: ["Marte", "Jupiter", "Venus", "Mercurio"], correctAnswer: 0 },
  { id: 42, question: "Cual es la funcion del sistema inmunologico?", options: ["Defender al cuerpo contra enfermedades", "Digerir alimentos", "Transportar oxigeno", "Producir hormonas"], correctAnswer: 0 },
  { id: 43, question: "Que tipo de onda es el sonido?", options: ["Onda mecanica longitudinal", "Onda electromagnetica", "Onda transversal", "Onda estacionaria"], correctAnswer: 0 },
  { id: 44, question: "Cual es el componente principal del aire que respiramos?", options: ["Nitrogeno (78%)", "Oxigeno (78%)", "CO2 (78%)", "Argon (78%)"], correctAnswer: 0 },
  { id: 45, question: "Que es un gen?", options: ["Unidad de herencia biologica", "Tipo de celula", "Tipo de tejido", "Organo del cuerpo"], correctAnswer: 0 },
  { id: 46, question: "Cual es la diferencia entre peso y masa?", options: ["La masa es constante, el peso varia con la gravedad", "Son lo mismo", "El peso es constante, la masa varia", "Ambos varian con la temperatura"], correctAnswer: 0 },
  { id: 47, question: "Que es la clorofila?", options: ["Pigmento verde de las plantas para la fotosintesis", "Tipo de vitamina", "Acido de las plantas", "Mineral del suelo"], correctAnswer: 0 },
  { id: 48, question: "Cual es la funcion del esofago?", options: ["Transportar alimentos de la boca al estomago", "Digerir proteinas", "Absorber nutrientes", "Filtrar toxinas"], correctAnswer: 0 },
  { id: 49, question: "Que es un volcan?", options: ["Abertura en la corteza terrestre por donde sale magma", "Tipo de montana", "Fuente de agua subterranea", "Formacion de hielo"], correctAnswer: 0 },
  { id: 50, question: "Cual es la ley de la conservacion de la energia?", options: ["La energia no se crea ni se destruye, solo se transforma", "La energia siempre se pierde", "La energia se crea constantemente", "La energia solo existe como calor"], correctAnswer: 0 },

  // --- MATEMATICAS (51-100) ---
  { id: 51, question: "Cuanto es la raiz cuadrada de 144?", options: ["12", "14", "10", "16"], correctAnswer: 0 },
  { id: 52, question: "Cual es el valor de Pi (aproximado)?", options: ["3.1416", "2.7182", "1.6180", "3.3333"], correctAnswer: 0 },
  { id: 53, question: "Cuanto es 15 x 15?", options: ["225", "215", "235", "245"], correctAnswer: 0 },
  { id: 54, question: "Que es un numero primo?", options: ["Un numero divisible solo por 1 y por si mismo", "Un numero par", "Un numero negativo", "Un numero decimal"], correctAnswer: 0 },
  { id: 55, question: "Cuantos grados tiene un angulo recto?", options: ["90 grados", "180 grados", "45 grados", "360 grados"], correctAnswer: 0 },
  { id: 56, question: "Cual es el resultado de 2 elevado a la 10?", options: ["1024", "512", "2048", "256"], correctAnswer: 0 },
  { id: 57, question: "Que es un triangulo equilatero?", options: ["Triangulo con tres lados iguales", "Triangulo con dos lados iguales", "Triangulo con un angulo recto", "Triangulo sin lados iguales"], correctAnswer: 0 },
  { id: 58, question: "Cuanto es el 25% de 200?", options: ["50", "40", "75", "25"], correctAnswer: 0 },
  { id: 59, question: "Cual es la formula del area de un circulo?", options: ["Pi x radio al cuadrado", "2 x Pi x radio", "Pi x diametro", "Radio x diametro"], correctAnswer: 0 },
  { id: 60, question: "Que es una fraccion impropia?", options: ["El numerador es mayor que el denominador", "El numerador es menor que el denominador", "Ambos son iguales", "El denominador es cero"], correctAnswer: 0 },
  { id: 61, question: "Cuanto es la suma de los angulos internos de un triangulo?", options: ["180 grados", "360 grados", "90 grados", "270 grados"], correctAnswer: 0 },
  { id: 62, question: "Que es el maximo comun divisor (MCD)?", options: ["El mayor numero que divide a dos o mas numeros", "El menor multiplo comun", "La suma de divisores", "El producto de factores"], correctAnswer: 0 },
  { id: 63, question: "Cuanto es 7 factorial (7!)?", options: ["5040", "720", "40320", "362880"], correctAnswer: 0 },
  { id: 64, question: "Cual es la propiedad conmutativa de la suma?", options: ["a + b = b + a", "a + 0 = a", "a + (-a) = 0", "a(b+c) = ab + ac"], correctAnswer: 0 },
  { id: 65, question: "Que es un poligono regular?", options: ["Poligono con todos los lados y angulos iguales", "Poligono con tres lados", "Poligono con cuatro lados", "Poligono irregular"], correctAnswer: 0 },
  { id: 66, question: "Cuanto es la raiz cubica de 27?", options: ["3", "9", "6", "4"], correctAnswer: 0 },
  { id: 67, question: "Que es una ecuacion lineal?", options: ["Ecuacion de primer grado", "Ecuacion de segundo grado", "Ecuacion exponencial", "Ecuacion logaritmica"], correctAnswer: 0 },
  { id: 68, question: "Cual es el perimetro de un cuadrado de lado 5?", options: ["20", "25", "10", "15"], correctAnswer: 0 },
  { id: 69, question: "Que es el teorema de Pitagoras?", options: ["a2 + b2 = c2 en un triangulo rectangulo", "La suma de angulos es 180", "El area es base por altura", "Pi es constante"], correctAnswer: 0 },
  { id: 70, question: "Cuanto es 0.5 expresado como fraccion?", options: ["1/2", "1/3", "1/4", "2/3"], correctAnswer: 0 },
  { id: 71, question: "Que es un numero racional?", options: ["Se puede expresar como fraccion a/b", "No tiene decimal", "Siempre es positivo", "Es un numero entero"], correctAnswer: 0 },
  { id: 72, question: "Cual es el volumen de un cubo de arista 3 cm?", options: ["27 cm3", "9 cm3", "18 cm3", "36 cm3"], correctAnswer: 0 },
  { id: 73, question: "Que es una funcion matematica?", options: ["Relacion que asigna a cada elemento un unico valor", "Una ecuacion sin solucion", "Un numero imaginario", "Una operacion basica"], correctAnswer: 0 },
  { id: 74, question: "Cuanto es el 10% de 450?", options: ["45", "40", "50", "55"], correctAnswer: 0 },
  { id: 75, question: "Que tipo de angulo mide mas de 90 y menos de 180 grados?", options: ["Obtuso", "Agudo", "Recto", "Llano"], correctAnswer: 0 },
  { id: 76, question: "Cual es el minimo comun multiplo de 4 y 6?", options: ["12", "24", "6", "8"], correctAnswer: 0 },
  { id: 77, question: "Que es una proporcion?", options: ["Igualdad entre dos razones", "Suma de fracciones", "Division inexacta", "Multiplicacion de enteros"], correctAnswer: 0 },
  { id: 78, question: "Cuantos lados tiene un hexagono?", options: ["6", "5", "7", "8"], correctAnswer: 0 },
  { id: 79, question: "Que es el valor absoluto de -7?", options: ["7", "-7", "0", "14"], correctAnswer: 0 },
  { id: 80, question: "Cual es la mediana de los numeros 3, 5, 7, 9, 11?", options: ["7", "5", "9", "35"], correctAnswer: 0 },
  { id: 81, question: "Que es un numero irracional?", options: ["No se puede expresar como fraccion exacta", "Siempre es negativo", "Siempre es par", "No existe"], correctAnswer: 0 },
  { id: 82, question: "Cuanto es 3/4 + 1/4?", options: ["1", "3/4", "1/2", "2/4"], correctAnswer: 0 },
  { id: 83, question: "Que es la pendiente de una recta?", options: ["La inclinacion de la recta respecto al eje X", "La longitud de la recta", "El punto donde cruza el eje Y", "La distancia entre dos puntos"], correctAnswer: 0 },
  { id: 84, question: "Cual es el area de un triangulo con base 10 y altura 6?", options: ["30", "60", "16", "36"], correctAnswer: 0 },
  { id: 85, question: "Que es un sistema de ecuaciones?", options: ["Conjunto de ecuaciones con variables comunes", "Una sola ecuacion compleja", "Una funcion cuadratica", "Un metodo de conteo"], correctAnswer: 0 },
  { id: 86, question: "Cuanto es (-3) x (-4)?", options: ["12", "-12", "-7", "7"], correctAnswer: 0 },
  { id: 87, question: "Que es un logaritmo?", options: ["Exponente al que hay que elevar la base", "Un tipo de fraccion", "Una raiz cuadrada", "Un numero complejo"], correctAnswer: 0 },
  { id: 88, question: "Cual es la suma de los numeros del 1 al 10?", options: ["55", "50", "45", "100"], correctAnswer: 0 },
  { id: 89, question: "Que figura tiene 4 lados iguales y 4 angulos rectos?", options: ["Cuadrado", "Rectangulo", "Rombo", "Trapecio"], correctAnswer: 0 },
  { id: 90, question: "Cuanto es 2/3 de 90?", options: ["60", "30", "45", "80"], correctAnswer: 0 },
  { id: 91, question: "Que es una variable en algebra?", options: ["Simbolo que representa un valor desconocido", "Un numero fijo", "Una operacion matematica", "Un resultado final"], correctAnswer: 0 },
  { id: 92, question: "Cual es el resultado de 10 elevado a 0?", options: ["1", "0", "10", "Indefinido"], correctAnswer: 0 },
  { id: 93, question: "Que es la probabilidad?", options: ["Medida de que tan posible es un evento", "Certeza absoluta", "Resultado final", "Operacion algebraica"], correctAnswer: 0 },
  { id: 94, question: "Cuantos vertices tiene un cubo?", options: ["8", "6", "12", "4"], correctAnswer: 0 },
  { id: 95, question: "Que es la moda en estadistica?", options: ["El valor que mas se repite", "El valor del medio", "El promedio", "El valor mayor"], correctAnswer: 0 },
  { id: 96, question: "Cuanto es 5 elevado a 3?", options: ["125", "15", "25", "75"], correctAnswer: 0 },
  { id: 97, question: "Que es un plano cartesiano?", options: ["Sistema de coordenadas con ejes X e Y", "Un tipo de figura geometrica", "Una ecuacion lineal", "Un metodo de calculo"], correctAnswer: 0 },
  { id: 98, question: "Cual es la formula de la distancia?", options: ["d = v x t", "d = m x a", "d = F / m", "d = m x g"], correctAnswer: 0 },
  { id: 99, question: "Que es un numero complejo?", options: ["Tiene parte real e imaginaria", "Es siempre negativo", "No tiene decimales", "Es un numero primo"], correctAnswer: 0 },
  { id: 100, question: "Cuantas caras tiene un dodecaedro?", options: ["12", "10", "8", "20"], correctAnswer: 0 },

  // --- HISTORIA (101-150) ---
  { id: 101, question: "En que ano llego Cristobal Colon a America?", options: ["1492", "1500", "1480", "1510"], correctAnswer: 0 },
  { id: 102, question: "Quien fue el primer presidente de los Estados Unidos?", options: ["George Washington", "Thomas Jefferson", "Abraham Lincoln", "John Adams"], correctAnswer: 0 },
  { id: 103, question: "En que ano inicio la Primera Guerra Mundial?", options: ["1914", "1918", "1939", "1900"], correctAnswer: 0 },
  { id: 104, question: "Cual fue la civilizacion que construyo las piramides de Giza?", options: ["Egipcia", "Romana", "Griega", "Mesopotamica"], correctAnswer: 0 },
  { id: 105, question: "En que ano cayo el Muro de Berlin?", options: ["1989", "1991", "1985", "1979"], correctAnswer: 0 },
  { id: 106, question: "Quien escribio 'Don Quijote de la Mancha'?", options: ["Miguel de Cervantes", "Federico Garcia Lorca", "Gabriel Garcia Marquez", "Pablo Neruda"], correctAnswer: 0 },
  { id: 107, question: "Que civilizacion invento la democracia?", options: ["Griega", "Romana", "Egipcia", "Persa"], correctAnswer: 0 },
  { id: 108, question: "En que ano termino la Segunda Guerra Mundial?", options: ["1945", "1944", "1946", "1943"], correctAnswer: 0 },
  { id: 109, question: "Quien fue Julio Cesar?", options: ["Lider militar y politico romano", "Emperador griego", "Faraon egipcio", "Rey persa"], correctAnswer: 0 },
  { id: 110, question: "Que evento marco el inicio de la Revolucion Francesa?", options: ["La toma de la Bastilla en 1789", "La coronacion de Napoleon", "El Tratado de Versalles", "La caida de Roma"], correctAnswer: 0 },
  { id: 111, question: "Quien pinto la Mona Lisa?", options: ["Leonardo da Vinci", "Miguel Angel", "Rafael", "Botticelli"], correctAnswer: 0 },
  { id: 112, question: "Que imperio construyo la Gran Muralla China?", options: ["Imperio Chino", "Imperio Mongol", "Imperio Japones", "Imperio Coreano"], correctAnswer: 0 },
  { id: 113, question: "En que siglo ocurrio el Renacimiento?", options: ["Siglos XV y XVI", "Siglos X y XI", "Siglos XVIII y XIX", "Siglo XX"], correctAnswer: 0 },
  { id: 114, question: "Quien fue Cleopatra?", options: ["Ultima reina del Antiguo Egipto", "Diosa griega", "Emperatriz romana", "Reina de Persia"], correctAnswer: 0 },
  { id: 115, question: "Que tratado puso fin a la Primera Guerra Mundial?", options: ["Tratado de Versalles", "Tratado de Paris", "Tratado de Roma", "Tratado de Viena"], correctAnswer: 0 },
  { id: 116, question: "Quien descubrio la penicilina?", options: ["Alexander Fleming", "Louis Pasteur", "Marie Curie", "Robert Koch"], correctAnswer: 0 },
  { id: 117, question: "Que civilizacion creo el sistema de escritura cuneiforme?", options: ["Sumeria", "Egipcia", "China", "India"], correctAnswer: 0 },
  { id: 118, question: "En que ano se declaro la independencia de Estados Unidos?", options: ["1776", "1789", "1800", "1750"], correctAnswer: 0 },
  { id: 119, question: "Quien fue Napoleon Bonaparte?", options: ["Emperador de Francia", "Rey de Inglaterra", "Zar de Rusia", "Rey de Espana"], correctAnswer: 0 },
  { id: 120, question: "Que era el feudalismo?", options: ["Sistema politico y social de la Edad Media", "Sistema economico moderno", "Gobierno democratico", "Republica antigua"], correctAnswer: 0 },
  { id: 121, question: "En que ano llego el hombre a la Luna?", options: ["1969", "1965", "1972", "1959"], correctAnswer: 0 },
  { id: 122, question: "Quien invento la imprenta?", options: ["Johannes Gutenberg", "Thomas Edison", "Benjamin Franklin", "Nikola Tesla"], correctAnswer: 0 },
  { id: 123, question: "Que fue la Revolucion Industrial?", options: ["Transformacion economica con maquinas y fabricas", "Guerra entre naciones", "Movimiento artistico", "Descubrimiento cientifico"], correctAnswer: 0 },
  { id: 124, question: "Quien fue Mahatma Gandhi?", options: ["Lider de la independencia de India", "Emperador de China", "Presidente de Sudafrica", "Rey de Japon"], correctAnswer: 0 },
  { id: 125, question: "Que fue el Holocausto?", options: ["Genocidio durante la Segunda Guerra Mundial", "Batalla medieval", "Revolucion politica", "Descubrimiento geografico"], correctAnswer: 0 },
  { id: 126, question: "En que continente se origino la civilizacion mesopotamica?", options: ["Asia", "Europa", "Africa", "America"], correctAnswer: 0 },
  { id: 127, question: "Quien fue Martin Luther King Jr.?", options: ["Lider del movimiento por los derechos civiles", "Presidente de EE.UU.", "General militar", "Cientifico"], correctAnswer: 0 },
  { id: 128, question: "Que fue la Guerra Fria?", options: ["Conflicto ideologico entre EE.UU. y la URSS", "Guerra entre Francia y Alemania", "Conquista de America", "Guerra religiosa"], correctAnswer: 0 },
  { id: 129, question: "En que ano se fundo Roma segun la tradicion?", options: ["753 a.C.", "500 a.C.", "100 a.C.", "1000 a.C."], correctAnswer: 0 },
  { id: 130, question: "Que fue la Inquisicion?", options: ["Institucion para perseguir herejias", "Movimiento cientifico", "Gobierno democratico", "Orden militar"], correctAnswer: 0 },
  { id: 131, question: "Quien fue Alejandro Magno?", options: ["Rey de Macedonia que conquisto un gran imperio", "Emperador romano", "Faraon de Egipto", "Filosofo griego"], correctAnswer: 0 },
  { id: 132, question: "Que ocurrio en Hiroshima en 1945?", options: ["Se lanzo la primera bomba atomica", "Se firmo un tratado de paz", "Hubo un terremoto", "Se construyo una muralla"], correctAnswer: 0 },
  { id: 133, question: "En que pais comenzo la Reforma Protestante?", options: ["Alemania", "Inglaterra", "Francia", "Italia"], correctAnswer: 0 },
  { id: 134, question: "Quien fue Simom Bolivar?", options: ["Libertador de varias naciones sudamericanas", "Rey de Espana", "Emperador de Brasil", "Presidente de Mexico"], correctAnswer: 0 },
  { id: 135, question: "Que era la Ruta de la Seda?", options: ["Red de rutas comerciales entre Asia y Europa", "Camino dentro de China", "Ruta maritima a America", "Sendero en Africa"], correctAnswer: 0 },
  { id: 136, question: "En que ano inicio la Revolucion Rusa?", options: ["1917", "1905", "1922", "1930"], correctAnswer: 0 },
  { id: 137, question: "Que fue el Imperio Otomano?", options: ["Imperio turco que duro seis siglos", "Imperio chino", "Imperio indio", "Imperio africano"], correctAnswer: 0 },
  { id: 138, question: "Quien fue Isaac Newton?", options: ["Fisico y matematico que descubrio la gravedad", "Filosofo griego", "Pintor renacentista", "Explorador espanol"], correctAnswer: 0 },
  { id: 139, question: "Que fue la peste negra?", options: ["Pandemia que devasto Europa en el siglo XIV", "Guerra medieval", "Erupcion volcanica", "Hambruna en Asia"], correctAnswer: 0 },
  { id: 140, question: "En que ano se abolo la esclavitud en Estados Unidos?", options: ["1865", "1800", "1900", "1776"], correctAnswer: 0 },
  { id: 141, question: "Que civilizacion construyo Machu Picchu?", options: ["Inca", "Maya", "Azteca", "Olmeca"], correctAnswer: 0 },
  { id: 142, question: "Quien fue Marie Curie?", options: ["Cientifica pionera en radioactividad", "Reina de Francia", "Escritora inglesa", "Pintora italiana"], correctAnswer: 0 },
  { id: 143, question: "Que fue la Declaracion Universal de los Derechos Humanos?", options: ["Documento de la ONU de 1948", "Constitucion de EE.UU.", "Tratado de Versalles", "Carta Magna"], correctAnswer: 0 },
  { id: 144, question: "En que pais se origino el budismo?", options: ["India", "China", "Japon", "Tailandia"], correctAnswer: 0 },
  { id: 145, question: "Que fue la era vikinga?", options: ["Periodo de exploracion y conquista escandinava", "Epoca del Imperio Romano", "Periodo de la Grecia clasica", "Era de los faraones"], correctAnswer: 0 },
  { id: 146, question: "Quien fue Albert Einstein?", options: ["Fisico que desarrollo la teoria de la relatividad", "Inventor de la bombilla", "Descubridor de America", "Filosofo aleman"], correctAnswer: 0 },
  { id: 147, question: "Que fue el apartheid?", options: ["Sistema de segregacion racial en Sudafrica", "Guerra civil en Europa", "Revolucion en Asia", "Movimiento artistico"], correctAnswer: 0 },
  { id: 148, question: "En que siglo se descubrio America?", options: ["Siglo XV", "Siglo XVI", "Siglo XIV", "Siglo XVII"], correctAnswer: 0 },
  { id: 149, question: "Que fue la Ilustracion?", options: ["Movimiento intelectual del siglo XVIII", "Estilo artistico medieval", "Religion antigua", "Sistema politico romano"], correctAnswer: 0 },
  { id: 150, question: "Quien fue Nelson Mandela?", options: ["Lider contra el apartheid y presidente de Sudafrica", "Rey de Nigeria", "General britanico", "Presidente de Kenia"], correctAnswer: 0 },

  // --- GEOGRAFIA (151-200) ---
  { id: 151, question: "Cual es el pais mas grande del mundo por superficie?", options: ["Rusia", "Canada", "China", "Estados Unidos"], correctAnswer: 0 },
  { id: 152, question: "Cual es el rio mas largo del mundo?", options: ["Nilo", "Amazonas", "Yangtse", "Misisipi"], correctAnswer: 0 },
  { id: 153, question: "Cual es la capital de Francia?", options: ["Paris", "Lyon", "Marsella", "Burdeos"], correctAnswer: 0 },
  { id: 154, question: "En que continente se encuentra Brasil?", options: ["America del Sur", "America del Norte", "Europa", "Africa"], correctAnswer: 0 },
  { id: 155, question: "Cual es la montana mas alta del mundo?", options: ["Monte Everest", "K2", "Kilimanjaro", "Mont Blanc"], correctAnswer: 0 },
  { id: 156, question: "Cual es el desierto mas grande del mundo?", options: ["Sahara", "Gobi", "Atacama", "Kalahari"], correctAnswer: 0 },
  { id: 157, question: "Cuantos continentes hay?", options: ["7", "5", "6", "8"], correctAnswer: 0 },
  { id: 158, question: "Cual es la capital de Japon?", options: ["Tokio", "Osaka", "Kioto", "Yokohama"], correctAnswer: 0 },
  { id: 159, question: "Que pais tiene forma de bota?", options: ["Italia", "Grecia", "Espana", "Portugal"], correctAnswer: 0 },
  { id: 160, question: "Cual es el lago mas grande del mundo?", options: ["Mar Caspio", "Lago Superior", "Lago Victoria", "Lago Baikal"], correctAnswer: 0 },
  { id: 161, question: "Cual es la capital de Australia?", options: ["Canberra", "Sidney", "Melbourne", "Brisbane"], correctAnswer: 0 },
  { id: 162, question: "En que oceano se encuentra la isla de Madagascar?", options: ["Oceano Indico", "Oceano Atlantico", "Oceano Pacifico", "Oceano Artico"], correctAnswer: 0 },
  { id: 163, question: "Cual es el pais con mas poblacion del mundo?", options: ["India", "China", "Estados Unidos", "Indonesia"], correctAnswer: 0 },
  { id: 164, question: "Donde se encuentra el Canal de Panama?", options: ["Panama", "Mexico", "Colombia", "Honduras"], correctAnswer: 0 },
  { id: 165, question: "Cual es la capital de Egipto?", options: ["El Cairo", "Alejandria", "Luxor", "Giza"], correctAnswer: 0 },
  { id: 166, question: "Que paises forman la Peninsula Iberica?", options: ["Espana y Portugal", "Francia y Espana", "Italia y Grecia", "Alemania y Austria"], correctAnswer: 0 },
  { id: 167, question: "Cual es el pais mas pequeno del mundo?", options: ["Vaticano", "Monaco", "San Marino", "Liechtenstein"], correctAnswer: 0 },
  { id: 168, question: "En que continente esta el Sahara?", options: ["Africa", "Asia", "America", "Europa"], correctAnswer: 0 },
  { id: 169, question: "Cual es la capital de Canada?", options: ["Ottawa", "Toronto", "Vancouver", "Montreal"], correctAnswer: 0 },
  { id: 170, question: "Que rio atraviesa Londres?", options: ["Tamesis", "Sena", "Danubio", "Rin"], correctAnswer: 0 },
  { id: 171, question: "Cual es la capital de Argentina?", options: ["Buenos Aires", "Cordoba", "Rosario", "Mendoza"], correctAnswer: 0 },
  { id: 172, question: "En que pais se encuentran las Cataratas del Niagara?", options: ["Canada y Estados Unidos", "Brasil y Argentina", "Mexico y Guatemala", "Peru y Bolivia"], correctAnswer: 0 },
  { id: 173, question: "Cual es el continente mas frio?", options: ["Antartida", "Europa", "Asia", "America del Norte"], correctAnswer: 0 },
  { id: 174, question: "Que estrecho separa Europa de Africa?", options: ["Estrecho de Gibraltar", "Estrecho de Bering", "Estrecho de Magallanes", "Canal de Suez"], correctAnswer: 0 },
  { id: 175, question: "Cual es la capital de Alemania?", options: ["Berlin", "Munich", "Hamburgo", "Frankfurt"], correctAnswer: 0 },
  { id: 176, question: "Que cordillera recorre Sudamerica?", options: ["Los Andes", "Los Alpes", "El Himalaya", "Las Rocosas"], correctAnswer: 0 },
  { id: 177, question: "Cual es el pais con mas islas del mundo?", options: ["Suecia", "Indonesia", "Filipinas", "Japon"], correctAnswer: 0 },
  { id: 178, question: "Donde se encuentra el Mar Muerto?", options: ["Entre Israel y Jordania", "En Turquia", "En Grecia", "En Egipto"], correctAnswer: 0 },
  { id: 179, question: "Cual es la capital de Brasil?", options: ["Brasilia", "Rio de Janeiro", "Sao Paulo", "Salvador"], correctAnswer: 0 },
  { id: 180, question: "Que pais es conocido como la tierra del sol naciente?", options: ["Japon", "China", "Corea", "India"], correctAnswer: 0 },
  { id: 181, question: "Cual es la selva tropical mas grande del mundo?", options: ["Amazonia", "Congo", "Borneo", "Daintree"], correctAnswer: 0 },
  { id: 182, question: "En que pais se encuentra la Torre Eiffel?", options: ["Francia", "Italia", "Espana", "Alemania"], correctAnswer: 0 },
  { id: 183, question: "Cual es la capital de Mexico?", options: ["Ciudad de Mexico", "Guadalajara", "Monterrey", "Cancun"], correctAnswer: 0 },
  { id: 184, question: "Que pais tiene la mayor extension de selva amazonica?", options: ["Brasil", "Peru", "Colombia", "Venezuela"], correctAnswer: 0 },
  { id: 185, question: "Cual es la capital de Rusia?", options: ["Moscu", "San Petersburgo", "Novosibirsk", "Vladivostok"], correctAnswer: 0 },
  { id: 186, question: "Que rio pasa por Paris?", options: ["Sena", "Tamesis", "Rin", "Danubio"], correctAnswer: 0 },
  { id: 187, question: "Cual es la isla mas grande del mundo?", options: ["Groenlandia", "Borneo", "Madagascar", "Sumatra"], correctAnswer: 0 },
  { id: 188, question: "En que pais se encuentra la Acrpolis?", options: ["Grecia", "Italia", "Turquia", "Egipto"], correctAnswer: 0 },
  { id: 189, question: "Cual es la capital de China?", options: ["Pekin (Beijing)", "Shanghai", "Hong Kong", "Canton"], correctAnswer: 0 },
  { id: 190, question: "Que pais esta formado por cuatro islas principales?", options: ["Japon", "Filipinas", "Indonesia", "Nueva Zelanda"], correctAnswer: 0 },
  { id: 191, question: "Donde se encuentra el Gran Canon?", options: ["Estados Unidos", "Mexico", "Canada", "Peru"], correctAnswer: 0 },
  { id: 192, question: "Cual es la capital de Italia?", options: ["Roma", "Milan", "Florencia", "Venecia"], correctAnswer: 0 },
  { id: 193, question: "Que pais tiene la linea costera mas larga?", options: ["Canada", "Australia", "Indonesia", "Rusia"], correctAnswer: 0 },
  { id: 194, question: "En que continente esta Nigeria?", options: ["Africa", "Asia", "America", "Europa"], correctAnswer: 0 },
  { id: 195, question: "Cual es la capital de Peru?", options: ["Lima", "Cusco", "Arequipa", "Trujillo"], correctAnswer: 0 },
  { id: 196, question: "Que mar esta entre Europa y Africa?", options: ["Mar Mediterraneo", "Mar Rojo", "Mar Negro", "Mar Caspio"], correctAnswer: 0 },
  { id: 197, question: "Cual es la cascada mas alta del mundo?", options: ["Salto Angel (Venezuela)", "Cataratas del Niagara", "Cataratas Victoria", "Cataratas del Iguazu"], correctAnswer: 0 },
  { id: 198, question: "En que pais se encuentra el Taj Mahal?", options: ["India", "Pakistan", "Iran", "Turquia"], correctAnswer: 0 },
  { id: 199, question: "Cual es la capital de Colombia?", options: ["Bogota", "Medellin", "Cali", "Cartagena"], correctAnswer: 0 },
  { id: 200, question: "Que rio es el mas caudaloso del mundo?", options: ["Amazonas", "Nilo", "Congo", "Ganges"], correctAnswer: 0 },

  // --- LENGUA Y LITERATURA (201-250) ---
  { id: 201, question: "Que es un sustantivo?", options: ["Palabra que nombra personas, animales o cosas", "Palabra que describe una accion", "Palabra que modifica al verbo", "Palabra que une oraciones"], correctAnswer: 0 },
  { id: 202, question: "Que es un verbo?", options: ["Palabra que expresa accion o estado", "Palabra que nombra cosas", "Palabra que describe cualidades", "Palabra que indica lugar"], correctAnswer: 0 },
  { id: 203, question: "Que es una metafora?", options: ["Figura literaria que identifica un concepto con otro", "Repeticion de sonidos", "Exageracion de una idea", "Pregunta sin respuesta"], correctAnswer: 0 },
  { id: 204, question: "Quien escribio 'Cien anos de soledad'?", options: ["Gabriel Garcia Marquez", "Mario Vargas Llosa", "Jorge Luis Borges", "Pablo Neruda"], correctAnswer: 0 },
  { id: 205, question: "Que es un adjetivo?", options: ["Palabra que califica o determina al sustantivo", "Palabra que nombra acciones", "Palabra que conecta oraciones", "Palabra que reemplaza al nombre"], correctAnswer: 0 },
  { id: 206, question: "Que es una oracion compuesta?", options: ["Oracion con dos o mas verbos", "Oracion con un solo verbo", "Oracion sin sujeto", "Oracion interrogativa"], correctAnswer: 0 },
  { id: 207, question: "Que es un sinonimo?", options: ["Palabra con significado similar a otra", "Palabra con significado opuesto", "Palabra sin significado", "Palabra que suena igual"], correctAnswer: 0 },
  { id: 208, question: "Que es un antonimo?", options: ["Palabra con significado contrario a otra", "Palabra con significado similar", "Palabra que suena igual", "Palabra compuesta"], correctAnswer: 0 },
  { id: 209, question: "Quien escribio 'Romeo y Julieta'?", options: ["William Shakespeare", "Charles Dickens", "Jane Austen", "Mark Twain"], correctAnswer: 0 },
  { id: 210, question: "Que es un pronombre?", options: ["Palabra que sustituye al nombre", "Palabra que describe", "Palabra que indica accion", "Palabra que une ideas"], correctAnswer: 0 },
  { id: 211, question: "Que es una hiperbole?", options: ["Exageracion de la realidad", "Comparacion entre dos cosas", "Repeticion de sonidos", "Personificacion de objetos"], correctAnswer: 0 },
  { id: 212, question: "Que es un adverbio?", options: ["Palabra que modifica al verbo, adjetivo u otro adverbio", "Palabra que nombra cosas", "Palabra que describe personas", "Palabra que une oraciones"], correctAnswer: 0 },
  { id: 213, question: "Que genero literario incluye novelas y cuentos?", options: ["Narrativo", "Lirico", "Dramatico", "Ensayo"], correctAnswer: 0 },
  { id: 214, question: "Que es un soneto?", options: ["Poema de 14 versos", "Poema de 10 versos", "Cuento corto", "Obra de teatro"], correctAnswer: 0 },
  { id: 215, question: "Que es la sintaxis?", options: ["Parte de la gramatica que estudia la estructura de las oraciones", "Estudio de los significados", "Estudio de los sonidos", "Estudio de la escritura"], correctAnswer: 0 },
  { id: 216, question: "Quien escribio 'La Odisea'?", options: ["Homero", "Virgilio", "Sofocles", "Platon"], correctAnswer: 0 },
  { id: 217, question: "Que es un parrafo?", options: ["Conjunto de oraciones sobre una idea principal", "Una sola oracion", "Una palabra clave", "Un titulo"], correctAnswer: 0 },
  { id: 218, question: "Que es la personificacion?", options: ["Atribuir cualidades humanas a objetos o animales", "Comparar dos cosas", "Exagerar una idea", "Repetir sonidos"], correctAnswer: 0 },
  { id: 219, question: "Que es un diptongo?", options: ["Union de dos vocales en una misma silaba", "Separacion de vocales", "Tres vocales juntas", "Una consonante doble"], correctAnswer: 0 },
  { id: 220, question: "Que es el sujeto de una oracion?", options: ["Quien realiza la accion", "La accion realizada", "El complemento directo", "El lugar de la accion"], correctAnswer: 0 },
  { id: 221, question: "Que tipo de narracion usa 'yo' como narrador?", options: ["Primera persona", "Segunda persona", "Tercera persona", "Narrador omnisciente"], correctAnswer: 0 },
  { id: 222, question: "Que es la rima?", options: ["Coincidencia de sonidos al final de los versos", "Repeticion de palabras", "Uso de metaforas", "Estructura de la oracion"], correctAnswer: 0 },
  { id: 223, question: "Que es una conjuncion?", options: ["Palabra que une palabras u oraciones", "Palabra que describe", "Palabra que nombra", "Palabra que indica accion"], correctAnswer: 0 },
  { id: 224, question: "Quien escribio 'El Principito'?", options: ["Antoine de Saint-Exupery", "Victor Hugo", "Albert Camus", "Julio Verne"], correctAnswer: 0 },
  { id: 225, question: "Que es una fabula?", options: ["Relato breve con moraleja, protagonizado por animales", "Novela larga", "Poema epico", "Obra de teatro"], correctAnswer: 0 },
  { id: 226, question: "Que es el predicado de una oracion?", options: ["Lo que se dice del sujeto", "Quien realiza la accion", "El complemento indirecto", "La preposicion principal"], correctAnswer: 0 },
  { id: 227, question: "Que son las palabras agudas?", options: ["Llevan el acento en la ultima silaba", "Llevan el acento en la penultima", "Llevan el acento en la antepenultima", "No llevan acento"], correctAnswer: 0 },
  { id: 228, question: "Que es un ensayo?", options: ["Texto argumentativo sobre un tema", "Poema lirico", "Cuento de ficcion", "Obra dramatica"], correctAnswer: 0 },
  { id: 229, question: "Que es la semantica?", options: ["Estudio del significado de las palabras", "Estudio de los sonidos", "Estudio de la estructura", "Estudio de la escritura"], correctAnswer: 0 },
  { id: 230, question: "Quien escribio '1984'?", options: ["George Orwell", "Aldous Huxley", "Ray Bradbury", "Isaac Asimov"], correctAnswer: 0 },
  { id: 231, question: "Que es una preposicion?", options: ["Palabra que establece relacion entre elementos", "Palabra que nombra", "Palabra que describe accion", "Palabra que sustituye"], correctAnswer: 0 },
  { id: 232, question: "Que es un genero lirico?", options: ["Genero que expresa sentimientos a traves de la poesia", "Genero que narra historias", "Genero para representar en escena", "Genero informativo"], correctAnswer: 0 },
  { id: 233, question: "Que son las palabras esdrujulas?", options: ["Acento en la antepenultima silaba, siempre con tilde", "Acento en la ultima silaba", "Acento en la penultima silaba", "No llevan acento"], correctAnswer: 0 },
  { id: 234, question: "Que es una leyenda?", options: ["Narracion tradicional con elementos fantasticos", "Texto cientifico", "Articulo periodistico", "Documento legal"], correctAnswer: 0 },
  { id: 235, question: "Que es el complemento directo?", options: ["Recibe directamente la accion del verbo", "Quien realiza la accion", "El lugar donde ocurre", "El tiempo de la accion"], correctAnswer: 0 },
  { id: 236, question: "Quien escribio 'La Divina Comedia'?", options: ["Dante Alighieri", "Francesco Petrarca", "Giovanni Boccaccio", "Niccolo Machiavelli"], correctAnswer: 0 },
  { id: 237, question: "Que es una onomatopeya?", options: ["Palabra que imita un sonido", "Figura de exageracion", "Tipo de rima", "Clase de sustantivo"], correctAnswer: 0 },
  { id: 238, question: "Que es un haiku?", options: ["Poema japones de tres versos", "Poema espanol de 14 versos", "Novela corta", "Tipo de fabula"], correctAnswer: 0 },
  { id: 239, question: "Que es la ortografia?", options: ["Conjunto de reglas para escribir correctamente", "Estudio de significados", "Estudio de sonidos", "Analisis de textos"], correctAnswer: 0 },
  { id: 240, question: "Que tipo de texto busca convencer al lector?", options: ["Argumentativo", "Narrativo", "Descriptivo", "Expositivo"], correctAnswer: 0 },
  { id: 241, question: "Que es un monologo?", options: ["Discurso de un solo personaje", "Dialogo entre dos", "Narracion en tercera persona", "Canto coral"], correctAnswer: 0 },
  { id: 242, question: "Que es una aliteracion?", options: ["Repeticion de sonidos consonantes", "Exageracion poetica", "Comparacion implicita", "Pregunta retorica"], correctAnswer: 0 },
  { id: 243, question: "Quien escribio 'Hamlet'?", options: ["William Shakespeare", "Moliere", "Anton Chejov", "Henrik Ibsen"], correctAnswer: 0 },
  { id: 244, question: "Que es un palimdromo?", options: ["Palabra o frase que se lee igual al derecho y al reves", "Palabra con dos significados", "Palabra sin significado", "Palabra extranjera"], correctAnswer: 0 },
  { id: 245, question: "Que es la coherencia en un texto?", options: ["Las ideas estan organizadas logicamente", "El texto tiene muchas palabras", "El texto es muy corto", "El texto tiene imagenes"], correctAnswer: 0 },
  { id: 246, question: "Que es un dialogo?", options: ["Conversacion entre dos o mas personas", "Texto escrito por una persona", "Descripcion de un lugar", "Narracion historica"], correctAnswer: 0 },
  { id: 247, question: "Que es la cohesion textual?", options: ["Conexion entre las partes del texto mediante conectores", "El tema principal del texto", "La extension del texto", "Las imagenes del texto"], correctAnswer: 0 },
  { id: 248, question: "Quien escribio 'Las mil y una noches'?", options: ["Autoria anonima/colectiva", "Homero", "Cervantes", "Shakespeare"], correctAnswer: 0 },
  { id: 249, question: "Que es una comparacion o simil?", options: ["Relacionar dos elementos usando 'como' o 'parece'", "Identificar un elemento con otro", "Exagerar una cualidad", "Dar vida a objetos"], correctAnswer: 0 },
  { id: 250, question: "Que es un campo semantico?", options: ["Grupo de palabras relacionadas por su significado", "Grupo de verbos conjugados", "Grupo de adjetivos", "Grupo de preposiciones"], correctAnswer: 0 },

  // --- TECNOLOGIA E INFORMATICA (251-300) ---
  { id: 251, question: "Que significa HTML?", options: ["HyperText Markup Language", "High Tech Modern Language", "Hyper Transfer Mail Link", "Home Tool Markup Language"], correctAnswer: 0 },
  { id: 252, question: "Que es un sistema operativo?", options: ["Software que gestiona los recursos del computador", "Un tipo de hardware", "Una red social", "Un navegador web"], correctAnswer: 0 },
  { id: 253, question: "Que significa CPU?", options: ["Unidad Central de Procesamiento", "Centro de Programacion Universal", "Circuito Principal Unificado", "Control de Programas Utiles"], correctAnswer: 0 },
  { id: 254, question: "Que es Internet?", options: ["Red global de computadoras interconectadas", "Un programa de computadora", "Un tipo de hardware", "Una base de datos"], correctAnswer: 0 },
  { id: 255, question: "Que es un algoritmo?", options: ["Conjunto de pasos para resolver un problema", "Un tipo de computadora", "Un lenguaje de programacion", "Una red social"], correctAnswer: 0 },
  { id: 256, question: "Que significa RAM?", options: ["Memoria de Acceso Aleatorio", "Red de Acceso Mundial", "Registro Automatico de Memoria", "Recurso de Almacenamiento Multiple"], correctAnswer: 0 },
  { id: 257, question: "Que es un navegador web?", options: ["Programa para acceder a paginas de Internet", "Sistema operativo", "Tipo de hardware", "Red de computadoras"], correctAnswer: 0 },
  { id: 258, question: "Que es un virus informatico?", options: ["Programa malicioso que dana el sistema", "Un componente del hardware", "Una actualizacion del sistema", "Un tipo de red"], correctAnswer: 0 },
  { id: 259, question: "Que es la nube (cloud computing)?", options: ["Servicios de almacenamiento y computacion por Internet", "Un tipo de hardware", "Una red local", "Un sistema operativo"], correctAnswer: 0 },
  { id: 260, question: "Que significa URL?", options: ["Localizador Uniforme de Recursos", "Unidad de Red Local", "Uso Regular del Lenguaje", "Utilidad para Redes Largas"], correctAnswer: 0 },
  { id: 261, question: "Que es un pixel?", options: ["Unidad minima de una imagen digital", "Un tipo de archivo", "Un programa", "Un tipo de memoria"], correctAnswer: 0 },
  { id: 262, question: "Que es software?", options: ["Programas e instrucciones de un computador", "Partes fisicas del computador", "Un tipo de red", "Un dispositivo de entrada"], correctAnswer: 0 },
  { id: 263, question: "Que es hardware?", options: ["Componentes fisicos del computador", "Programas del computador", "Un tipo de virus", "Una red de Internet"], correctAnswer: 0 },
  { id: 264, question: "Que significa WiFi?", options: ["Wireless Fidelity (Fidelidad Inalambrica)", "Wired File Integration", "Web Finder Interface", "Wide Frequency Input"], correctAnswer: 0 },
  { id: 265, question: "Que es un byte?", options: ["Unidad de informacion de 8 bits", "Un tipo de programa", "Un componente fisico", "Una medida de velocidad"], correctAnswer: 0 },
  { id: 266, question: "Que es inteligencia artificial?", options: ["Simulacion de inteligencia humana por maquinas", "Un tipo de computadora", "Un lenguaje de programacion", "Hardware avanzado"], correctAnswer: 0 },
  { id: 267, question: "Que es una base de datos?", options: ["Coleccion organizada de datos", "Un tipo de hardware", "Un navegador web", "Un sistema operativo"], correctAnswer: 0 },
  { id: 268, question: "Que es un firewall?", options: ["Sistema de seguridad de red", "Un tipo de virus", "Un programa de diseno", "Un componente del procesador"], correctAnswer: 0 },
  { id: 269, question: "Que significa GPS?", options: ["Sistema de Posicionamiento Global", "Programa General de Software", "Graficos para Sistemas Personales", "Gestion de Procesos del Sistema"], correctAnswer: 0 },
  { id: 270, question: "Que es un servidor?", options: ["Computadora que provee servicios a otras", "Un tipo de monitor", "Un programa de diseno", "Un dispositivo de entrada"], correctAnswer: 0 },
  { id: 271, question: "Que es programacion?", options: ["Proceso de crear instrucciones para computadoras", "Reparar hardware", "Conectar redes", "Disenar paginas web"], correctAnswer: 0 },
  { id: 272, question: "Que es un disco duro?", options: ["Dispositivo de almacenamiento permanente", "Tipo de memoria temporal", "Un procesador", "Un monitor"], correctAnswer: 0 },
  { id: 273, question: "Que es ciberseguridad?", options: ["Proteccion de sistemas y datos contra ataques", "Tipo de virus", "Red de computadoras", "Sistema operativo"], correctAnswer: 0 },
  { id: 274, question: "Que es un router?", options: ["Dispositivo que dirige trafico de red", "Un tipo de monitor", "Un programa antivirus", "Un componente de la CPU"], correctAnswer: 0 },
  { id: 275, question: "Que significa IoT?", options: ["Internet de las Cosas", "Interior de la Tecnologia", "Informacion Online Total", "Integracion de Telefonos"], correctAnswer: 0 },
  { id: 276, question: "Que es el blockchain?", options: ["Tecnologia de registro distribuido e inmutable", "Un tipo de virus", "Un navegador web", "Un sistema operativo"], correctAnswer: 0 },
  { id: 277, question: "Que es un SSD?", options: ["Disco de Estado Solido", "Sistema de Seguridad Digital", "Software de Sistema Distribuido", "Servidor de Datos Seguros"], correctAnswer: 0 },
  { id: 278, question: "Que es machine learning?", options: ["Aprendizaje automatico por maquinas", "Un tipo de hardware", "Un lenguaje de programacion", "Un sistema operativo"], correctAnswer: 0 },
  { id: 279, question: "Que es un QR code?", options: ["Codigo de barras bidimensional", "Un tipo de virus", "Un programa", "Una red social"], correctAnswer: 0 },
  { id: 280, question: "Que es la realidad virtual?", options: ["Entorno simulado generado por computadora", "Un tipo de monitor", "Una red social", "Un sistema operativo"], correctAnswer: 0 },
  { id: 281, question: "Que es un sistema binario?", options: ["Sistema numerico de base 2 (0 y 1)", "Sistema de 10 digitos", "Sistema de letras", "Sistema hexadecimal"], correctAnswer: 0 },
  { id: 282, question: "Que es CSS?", options: ["Lenguaje para dar estilo a paginas web", "Lenguaje de programacion", "Sistema operativo", "Base de datos"], correctAnswer: 0 },
  { id: 283, question: "Que es un dominio web?", options: ["Nombre unico que identifica un sitio web", "Un tipo de servidor", "Un programa", "Un virus"], correctAnswer: 0 },
  { id: 284, question: "Que es la realidad aumentada?", options: ["Superpone elementos digitales al mundo real", "Entorno completamente virtual", "Un tipo de red", "Un sistema operativo"], correctAnswer: 0 },
  { id: 285, question: "Que es Python?", options: ["Lenguaje de programacion de alto nivel", "Un tipo de hardware", "Un navegador web", "Un sistema operativo"], correctAnswer: 0 },
  { id: 286, question: "Que es un backup?", options: ["Copia de seguridad de datos", "Un tipo de virus", "Un programa de diseno", "Un componente fisico"], correctAnswer: 0 },
  { id: 287, question: "Que es el phishing?", options: ["Tecnica fraudulenta para robar datos personales", "Un programa antivirus", "Un tipo de red", "Un navegador seguro"], correctAnswer: 0 },
  { id: 288, question: "Que es USB?", options: ["Bus Universal en Serie", "Unidad de Software Basico", "Utilidad del Sistema Binario", "Union de Servidores Base"], correctAnswer: 0 },
  { id: 289, question: "Que es un hashtag?", options: ["Etiqueta precedida por # para categorizar contenido", "Un tipo de virus", "Un componente de hardware", "Un sistema de archivos"], correctAnswer: 0 },
  { id: 290, question: "Que es la banda ancha?", options: ["Conexion a Internet de alta velocidad", "Un tipo de cable", "Un componente del procesador", "Un programa"], correctAnswer: 0 },
  { id: 291, question: "Que es JavaScript?", options: ["Lenguaje de programacion para web", "Un tipo de cafe", "Un sistema operativo", "Un navegador"], correctAnswer: 0 },
  { id: 292, question: "Que es un emoji?", options: ["Icono digital que expresa emociones", "Un tipo de virus", "Un programa", "Un archivo de texto"], correctAnswer: 0 },
  { id: 293, question: "Que es el 5G?", options: ["Quinta generacion de redes moviles", "Quinto modelo de computadora", "Un tipo de software", "Un lenguaje de programacion"], correctAnswer: 0 },
  { id: 294, question: "Que es un podcast?", options: ["Contenido de audio digital distribuido por Internet", "Un tipo de video", "Un programa de TV", "Un archivo de texto"], correctAnswer: 0 },
  { id: 295, question: "Que es la computacion cuantica?", options: ["Computacion basada en principios de mecanica cuantica", "Computacion normal mas rapida", "Un tipo de red", "Un sistema operativo"], correctAnswer: 0 },
  { id: 296, question: "Que es un API?", options: ["Interfaz de Programacion de Aplicaciones", "Un tipo de hardware", "Un navegador", "Un sistema de archivos"], correctAnswer: 0 },
  { id: 297, question: "Que es el streaming?", options: ["Transmision de contenido multimedia en tiempo real", "Descarga de archivos", "Un tipo de virus", "Un componente del PC"], correctAnswer: 0 },
  { id: 298, question: "Que es Git?", options: ["Sistema de control de versiones", "Un navegador web", "Un sistema operativo", "Un tipo de base de datos"], correctAnswer: 0 },
  { id: 299, question: "Que es un chatbot?", options: ["Programa que simula una conversacion", "Un tipo de virus", "Un componente de hardware", "Un archivo de audio"], correctAnswer: 0 },
  { id: 300, question: "Que es la huella digital?", options: ["Rastro unico de actividad en Internet", "Un tipo de contrasena", "Un programa de seguridad", "Un componente del teclado"], correctAnswer: 0 },
]

export default questionBank
